#!/usr/bin/awk -f
#
# Copyright (c) 2016 Douglas G. Scofield, Uppsala University
# douglas.scofield@ebc.uu.se
# douglasgscofield@gmail.com
#
# This code is covered by the Gnu GPLv2, please see LICENSE.
# Bugs and suggestions to https://github.com/douglasgscofield/tinyutils/issues.
#
# Only show the requested line.  This will be expanded.
#
# CHANGELOG
# 2016-07-27 : create the script


BEGIN { 
    # parameters
    line = 0;           # which line do we show?
    min = 0;           # which line do we show?
    max = 0;           # which line do we show?
}

{
    if (NR == 1) {
        if (!line && !min && !max) {
            print "no line(s) specified" > "/dev/stderr";
            exit 1;
        } else if (line < 0 || min < 0 || max < 0) {
            print "line specifiers must be 0 or positive" > "/dev/stderr";
            exit 1;
        } else if (max && min > max) {
            print "if max specified, max must be >= min" > "/dev/stderr";
            exit 1;
        } else if (min && max && min > max) {
            print "if min and max specified, min must be <= max" > "/dev/stderr";
            exit 1;
        }
    }
    if (line && NR == line) {
        print;
    } else if (min && NR >= min) {
        if (!max || (max && NR <= max)) {
            print;
        }
    } else if (max && NR <= max) {
        if (!min || (min && NR >= max)) {
            print;
        }
    } else if (((line && NR > line) && (!max || (max && NR > max))) ||
               (!line && max && NR > max)) {
        # no more lines to show
        exit 0;
    }
}
