#!/usr/bin/awk -f
#
# Copyright (c) 2016 Douglas G. Scofield, Uppsala University
# douglas.scofield@ebc.uu.se
# douglasgscofield@gmail.com
#
# This code is covered by the Gnu GPLv2, please see LICENSE.
# Bugs and suggestions to https://github.com/douglasgscofield/tinyutils/issues.
#
# Reports which line contains a column having the given value
#
# CHANGELOG
# 2017-08-11 : add inverse= option
# 2016-07-27 : create the script


BEGIN { 
    # parameters
    FS = "\t"; 
    OFS = "\t"; 
    header = 0;        # does the input have a header? if so how many lines?
    skip_comment = 1;  # skip '#' lines on input
    val = "";          # the value to match
    col = 1;           # which column do we lwhich?
    inverse = 0;       # print numbers of lines that do not contain the value in the specified column
}

{
    if (NR <= header) { print; next; }
    if (skip_comment && $0 ~ /^#/) { print; next; }

    if (NF < col) {
        print "on input line " NR " missing requested column" > "/dev/stderr";
        next;
    }
    if ($(col) == val) {
        if (inverse == 0)
            print NR;
    } else if (inverse == 1)
        print NR;
}

