#!/usr/bin/awk -f
#
# Copyright (c) 2012 Douglas G. Scofield, Umeå Plant Sciences Centre, Umeå, Sweden
# douglas.scofield@plantphys.umu.se
# douglasgscofield@gmail.com
#
# No warranty is implied or assumed by this code.  Please send bugs, suggestions etc.
#
# Compute the mean of a set of numbers
#
# CHANGELOG
# 2012-12-03 : clean the script up a bit


BEGIN { 
    # parameters
    FS = "\t"; 
    OFS = "\t"; 
    n = 0;
    sum = 0;
    header = 0;        # does the input have a header? if so how many lines?
    skip_comment = 1;  # skip '#' lines on input
}

{
    if (NR <= header) { print; next; }
    if (skip_comment && $0 ~ /^#/) { print; next; }

    ++n;
    sum += $1;
}

END {
    if (n <= 0)
        print "No input";
    else
        print (sum / n);
}
