#!/usr/bin/awk -f
#
# Copyright (c) 2016 Douglas G. Scofield, Uppsala University
# douglas.scofield@ebc.uu.se
# douglasgscofield@gmail.com
#
# This code is covered by the Gnu GPLv2, please see LICENSE.
# Bugs and suggestions to https://github.com/douglasgscofield/tinyutils/issues.
#
# Print the contents of each column prefixed by the column number
#
# CHANGELOG
# 2016-02-16 : do not print header and comment lines as they are skipped
# 2016-02-11 : create the script


BEGIN { 
    # parameters
    IFS="\t";          # default to tab column separators
    header = 0;        # does the input have a header? if so how many lines?
    skip_comment = 1;  # skip '#' lines on input
    lines = 1;         # the number of lines to do this for
    sep = ":";
}

{
    if (NR <= header) { next; }
    if (skip_comment && $0 ~ /^#/) { next; }
    if (lines > 0) {
        for (col = 1; col <= NF; ++col) {
            $(col) = col sep $(col);
        }
        OFS = IFS;
        print;
        --lines;
    }
}

